Replace in-house logger with spdlog.
performous/performous pull request #1011
Opened 2024-10-28 21:22 UTC by Lord-Kamina

Our logger is terrible. I don't think anyone disputes this.
Spdlog will likely provide better performance, and a much nicer API, plus it's available on pretty much every platform and is header-only.

### What does this PR do?

### Closes Issue(s)

### Motivation

### More

- [ ] Added/updated documentation

### Additional Notes

2024-10-28 21:23 UTC, Lord-Kamina commented
Opened the first draft chiefly to see how it's doing on CI.

2025-01-20 18:09 UTC, Lord-Kamina commented
I have cleaned up the commit history a bit and I think this is now ready for review, although I would like to merge #1025 before this one.

2025-01-28 18:44 UTC, Baklap4 requested changes
a couple of code things i aleady saw; will do some playtesting at a late rpoint.

Most changes are changing the message from clog to spdlog so that's all just fine.

I do wonder (but will also see within playtesting) how is the memory usage compared to what we had before and how's the cpu usage?

Idealy these should be equal or better compared to what we had

2025-01-28 19:29 UTC, Lord-Kamina commented on .github/workflows/windows.yml
> +          pkgs: "\"aubio[core,tools]\" \"boost-algorithm[core]\" \"boost-align[core]\" \"boost-any[core]\" \"boost-array[core]\" \"boost-assert[core]\" \"boost-asio\" \"boost-atomic[core]\" \"boost-b
I am not sure if this possible... it might be now, but at least until a few years ago it wasn't doable.

2025-01-28 19:35 UTC, Lord-Kamina commented on game/logger_subsystem.hh
> +	};
The values are never exposed raw to the user and they're only relevant in the context of a specific run of the app, and so we don't accidentally use systems that don't exist so I think that is not really necessary. It doesn't really matter if the underlying values change, as long as whoever adds a new system makes sure to add a corresponding case to the functions that transform them to text.

2025-02-08 13:16 UTC, Lord-Kamina commented
Anything else, @Baklap4 ?

2025-03-31 11:53 UTC, Lord-Kamina commented
> Anything else, @Baklap4 ?

I had fixes done but uncommited, waiting for you so I we could avoid a million "address comments" commits.

Have you had any chance to test this?

2025-04-12 10:36 UTC, Baklap4 approved these changes

2025-04-14 19:53 UTC, Baklap4 commented
Re-running the job on mac will fix the mac failure (i've updated cmake-minimum-version in performous/ced -> https://github.com/performous/compact_enc_det/commit/28f46c18c60b851773b0ff61f3ce416fb09adcf3)

2025-04-28 06:21 UTC, Baklap4 approved these changes

2025-05-30 15:26 UTC, merged