Use new ppa from Kamina
performous/performous pull request #661
Opened 2021-08-23 17:25 UTC by Baklap4

### What does this PR do?

Uses new ppa @Lord-Kamina provided

### Closes Issue(s)

Fixes cpack deb creation

2021-08-23 17:34 UTC, Lord-Kamina requested changes
You forgot to modify the job titles and the environment variables.

2021-09-02 19:54 UTC, Baklap4 commented
Removed `In Progress`. Added `Needs Testing` and `Ready for Review`. The build + deb generation succeeds now 🎉

2021-09-03 22:37 UTC, Lord-Kamina approved these changes

2021-09-03 22:37 UTC, Lord-Kamina commented
I think we're good with this once it finishes checking the rebase?

2021-09-04 10:09 UTC, merged