Fix possible invalid memory access
performous/performous pull request #694
Opened 2022-01-01 11:13 UTC by OznOg

The function tellg() can return -1 making the overall vector size to be
0 and thus accessing the back element is invalid.

g++ 11 complains about it and reports a warning

This patch adds an extra check in case tellg fails

2022-03-28 23:59 UTC, twollgam requested changes
LGTM except the indent.

2022-03-28 23:59 UTC, twollgam commented on game/glshader.cc
> +                if (size == static_cast<decltype(size)>(-1)) throw std::runtime_error(std::string("Cannot get size of file ") + filepath);
Use 2 tabs here for indent.

2022-03-29 07:22 UTC, Baklap4 commented
I'll try to compile it later today

2022-03-30 19:11 UTC, OznOg commented on game/glshader.cc
> +                if (size == static_cast<decltype(size)>(-1)) throw std::runtime_error(std::string("Cannot get size of file ") + filepath);
grumpf

2022-04-02 18:59 UTC, Baklap4 approved these changes
LGTM

2022-04-02 19:04 UTC, merged