Bugfix/design flaw in ring buffer
performous/performous pull request #795
Opened 2022-07-23 10:12 UTC by twollgam

### What does this PR do?

Fixes a design flaw in class RingBuffer. The size cannot reach capacity but this is expected. This PR will fix that.

Additionally RingBuffer is moved to own header file, implementation and declaration is divided and forward declarations for Analyzer is used to prevent to much recompilation while developing.

Add unittests for RingBuffer class.
 
### Closes Issue(s)

None.

### Motivation

Classes should work as expected.

2022-09-01 07:33 UTC, Baklap4 commented
I'll take a look at this tonight! Thanks for the PR already :)

2022-09-01 16:17 UTC, Baklap4 requested changes
Overall looks alright to me. Some minor items to fix as it's mainly refactoring and moving stuff

2022-09-01 16:17 UTC, Baklap4 commented on game/audio.cc
> +		self = std::make_unique<Impl>();
please allign properly

2022-09-01 16:17 UTC, Baklap4 commented on game/audio.hh
> +		// static because Port audio once for the whole software lifetime
Align properly

2022-09-01 16:17 UTC, Baklap4 commented on game/pitch.hh
> +
please do not define double private sections
Do keep the methods together and fields together though

I'd prefer the order of method - member

2022-09-01 16:17 UTC, Baklap4 commented on game/ringbuffer.hh
> +  private:
please do not define double private sections
Do keep the methods together and fields together though

I'd prefer the order of method - member

2022-09-01 16:17 UTC, Baklap4 commented on game/pitch.hh
> +static const unsigned FFT_P = 12;
Why did you increase this value?

2022-09-01 17:37 UTC, twollgam commented on game/pitch.hh
> +static const unsigned FFT_P = 12;
Ups, good catch. Accident :-(

2022-09-04 19:46 UTC, ooshlablu commented
Tested with vocals + guitar with the deb and appimage on Ubuntu 20.04. Didn't notice any difference in gameplay, which I think is the point. LGTM

2022-09-06 18:00 UTC, Baklap4 approved these changes
LGTM, discussions have been addressed! Thanks

2022-09-07 01:59 UTC, merged