improve guitar frets, fix shader lighting model
performous/performous pull request #817
Opened 2022-09-04 15:15 UTC by qreeves

### What does this PR do?

- Adds *basic* MTL support for OBJ files.
- Adds support for color keyed vertices on `3dobject`.
- Adds new `3dobjkey` shader which uses the the keyed parameters.
- Fixes the lighting model in `core.frag` so shading is correct.

### Motivation

Wanting to improve the look and feel of Performous, especially with regard to instrument tracks.

### Additional Notes

As OBJ files do not natively support color keying, any material name starting with `ColorKey` will be set as a keyed color. This allows having fret objects which do not color the entire model, but rather specific sections of the model which take on color with this attribute.

2022-09-04 18:39 UTC, ooshlablu commented
Tested with vocals + guitar with the deb and appimage on Ubuntu 20.04. Didn't notice any issues. Polish looks great!

2022-09-12 12:41 UTC, Lord-Kamina requested changes
I don't see any issues other than those erroneous indents. @Baklap4?

2022-09-12 12:41 UTC, Lord-Kamina commented on data/shaders/core.frag
> +		power *= pow(spec, 100);
Tabs shall be your undoing 😂

2022-09-12 12:42 UTC, Lord-Kamina commented on data/shaders/core.frag
> +		power *= pow(spec, 100);
I seem to have pointed my comment anywhere but where the actual issue is.

2022-09-12 15:50 UTC, Baklap4 commented
LGTM except for above mentioned indents

2022-09-13 18:11 UTC, Baklap4 requested changes
I'm not quite sure why the workflow fails on this branch...
Is it possible to rebase this branch on latest master and see if anything changes?

2022-09-13 18:30 UTC, qreeves commented
My branch was force pushed and I've officially lost interest in contributing now.

2022-09-13 18:30 UTC, closed without merging

2022-09-13 19:06 UTC, Lord-Kamina commented
@qreeves I don't think it was force-pushed, except possibly rebased against master (which shows up as a force push but is done from the PR interface itself) because the repository settings required that in order for it to be mergeable? (And we've turned that off now)

2022-09-13 19:08 UTC, Lord-Kamina commented
@qreeves i.e. This: 
![5D5E2C95-015E-4586-87BE-23DA36F66EA0](https://user-images.githubusercontent.com/6446892/189988768-55fc2b59-52b2-425d-a457-edcad7ddf9a8.png) (old picture, for reference)