Fix sigsegv in drawCovers().
performous/performous pull request #835
Opened 2022-11-08 16:28 UTC by Lord-Kamina

### What does this PR do?

Fixes a potential `nullptr` dereference in `drawCovers`.

@ooshlablu noticed a crash in screeen_songs while testing #545.

Upon investigating I reproduced it and tracked it here. No idea why it's not causing a crash on master but did on the PR.

### Closes Issue(s)

### Motivation

QA

### More

- [ ] Added/updated documentation

### Additional Notes

2023-02-17 18:00 UTC, Baklap4 submitted a review, later dismissed
LGTM, please rebase on latest and this can get merged

2023-02-17 18:19 UTC, Baklap4 approved these changes

2023-02-17 21:18 UTC, ooshlablu requested changes
I just tested both the debs and AppImage, and they load fine, but pressing "Enter" to get into the song selection screen causes the game to exit with "Aborted"

This is the only info I have from running with `--log=debug`:
```
controllers/debug: processing (keyboard 0 instrument 0) GENERIC START (NavButton::START) value=1
audio/debug: playMusic() -> 0x55df961655f0
image/debug: Loading SVG: /tmp/.mount_Perforz7m7fq/usr/share/games/performous/themes/default/songs_bg.svg
audio/debug: preload done -> playing 0x55df961655f0
image/debug: Saving PNG: /home/ooshlablu/.cache/performous/misc/tmp/.mount_Perforz7m7fq/usr/share/games/performous/themes/default/songs_bg.svg.cache_1.50.premul.png
Aborted
```
Here's the output from `gdb`:
```
songs/notice: Done Loading. Loaded 4250 Songs.
songs/notice: Done Caching.
[Thread 0x7fffdffff640 (LWP 12578) exited]
[Thread 0x7fffd79fe640 (LWP 12582) exited]
[Thread 0x7fffd81ff640 (LWP 12581) exited]
[Thread 0x7fff71743640 (LWP 12602) exited]
[Thread 0x7fff72782640 (LWP 12601) exited]
[Thread 0x7fff80f42640 (LWP 12599) exited]
[Thread 0x7fff82fc0640 (LWP 12597) exited]
[Thread 0x7fff91743640 (LWP 12595) exited]
[Thread 0x7fff737c1640 (LWP 12600) exited]
[Thread 0x7fff81f81640 (LWP 12598) exited]
[Thread 0x7fff83fff640 (LWP 12596) exited]
[Thread 0x7fff92782640 (LWP 12594) exited]
[Thread 0x7fff937c1640 (LWP 12593) exited]
[Thread 0x7fffd4978640 (LWP 12592) exited]
[Thread 0x7fffd59b7640 (LWP 12591) exited]
[Thread 0x7fff5ffff640 (LWP 12603) exited]

Thread 1 "performous" received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737048239360) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737048239360)
    at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737048239360)
    at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737048239360, signo=signo@entry=6)
    at ./nptl/pthread_kill.c:89
#3  0x00007ffff3442476 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/posix/raise.c:26
#4  0x00007ffff34287f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff342871b in __assert_fail_base (
    fmt=0x7ffff35dd150 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=0x7ffff75b3768 "0 && \"Couldn't find current GLX or EGL context.\\n\"", file=0x7ffff75b36c0 "../src/dispatch_common.c", line=863, 
    function=<optimized out>) at ./assert/assert.c:92
#6  0x00007ffff3439e96 in __GI___assert_fail (
    assertion=0x7ffff75b3768 "0 && \"Couldn't find current GLX or EGL context.\\n\"", file=0x7ffff75b36c0 "../src/dispatch_common.c", line=863, 
    function=0x7ffff75b37a0 "epoxy_get_proc_address") at ./assert/assert.c:101
#7  0x00007ffff7591a9f in ?? ()
   from /tmp/.mount_PerforAmaGPc//usr/lib/x86_64-linux-gnu/libepoxy.so.0
#8  0x00007ffff75676da in ?? ()
   from /tmp/.mount_PerforAmaGPc//usr/lib/x86_64-linux-gnu/libepoxy.so.0
#9  0x000055555568194a in Shader::~Shader() ()
--Type <RET> for more, q to quit, c to continue without paging--
#10 0x00005555556d3f1e in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::unique_ptr<Shader, std::default_delete<Shader> > >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::unique_ptr<Shader, std::default_delete<Shader> > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::unique_ptr<Shader, std::default_delete<Shader> > > > >::_M_erase(std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::unique_ptr<Shader, std::default_delete<Shader> > > >*) ()
#11 0x00005555557df22b in Window::~Window() ()
#12 0x00005555555d247d in mainLoop(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) [clone .cold] ()
#13 0x00005555555f0f04 in main ()
(gdb) quit
A debugging session is active.

	Inferior 1 [process 12551] will be killed.

Quit anyway? (y or n) y
```

2023-02-20 17:24 UTC, twollgam commented
@ooshlablu the crash in destructor  of Window should be fixed with #865

2023-03-03 22:50 UTC, ooshlablu reviewed
I think it should be good to go now that 865 has been merged

2023-05-13 21:00 UTC, Baklap4 commented
Let's get this merged :)

2023-09-24 16:09 UTC, Baklap4 commented
Let's bring this up to date with last master

2023-09-24 16:32 UTC, ooshlablu commented
FWIW I still experience this pretty often, so definitely worth a merge.

2023-10-04 19:11 UTC, Baklap4 commented
Made this up to date. Let's merge this when actions are green

2023-10-04 19:42 UTC, merged