Replace boost-functions
performous/performous pull request #974
Opened 2024-02-28 20:46 UTC by twollgam

### What does this PR do?

Remove more boost functions by std:: or own replacements to get more independent from boost libs.

### Closes Issue(s)

None, but related to #39 .

2024-03-29 11:27 UTC, Baklap4 requested changes

2024-03-29 11:27 UTC, Baklap4 commented on testing/utiltest.cc
> +    //EXPECT_EQ("02:01:00 1970-01-01", format(time, "%T %F"));
Maybe we should add a compiler-if-check here so they are exclued for mingw (or we delete these two entirely) 

i don't like commented code which does nothing :P

2024-03-30 09:31 UTC, Baklap4 approved these changes
Let's get this tested, and see if anything weird shows up if not, the review is approved! @ooshlablu

2024-05-01 17:49 UTC, BWagener commented
Tested on windows, looks good to me.

2024-05-04 14:09 UTC, Baklap4 approved these changes

2024-05-04 14:09 UTC, merged