Visual Studio TestExplorer detects the google tests
performous/performous pull request #986
Opened 2024-04-20 11:23 UTC by twollgam

### What does this PR do?

This PR adds files so that the Visual Studio TestExplorer  detects the google tests.

The anonymous namespaces will be removed. The TestExplorer shows the tests under <Empty Namespace>.  Else it is mixed with "anonymous namespace".

![image](https://github.com/performous/performous/assets/55762382/1fd7c58b-45b2-4bf3-8dfb-55f3a9eee54e)

### Closes Issue(s)

None

### Motivation

The TestExplorer makes it easy to run single tests and debug them.

2024-04-20 11:28 UTC, twollgam commented
@Baklap4 would be nice if you can test this one , review and merge it. There is no productive code involved. 

Cause it is very helpful while developing, I hope you can do it soon.

2024-04-21 17:15 UTC, Baklap4 requested changes
Not sure the testenvironments.json is needed since it doesn't contain info.

As for the rest it looks good thanks that you've enabled the test explorer! 🎉

2024-04-21 17:25 UTC, twollgam commented on testEnvironments.json
> +﻿{
Don't where it comes from, but it is not needed 👍 Removed it ...

2024-04-21 17:44 UTC, Baklap4 commented
Let's await #981 as i think i found the reason why macos build is failing....

2024-04-21 18:49 UTC, Baklap4 approved these changes

2024-05-04 08:18 UTC, Baklap4 commented
Can be rebased so that it can be merged, maybe still await 981 before rebasing so you dont have to build twice

2024-05-04 10:17 UTC, merged